name: CI

env:
  build_cmd: xcodebuild CODE_SIGNING_ALLOWED="NO" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_IDENTITY="" -target

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Select Xcode version (14.2)
        run: |
          sudo xcode-select --switch /Applications/Xcode_14.2.app
      
      - name: Build library
        run: |
          ${{ env.build_cmd }} ellekit
          
          mkdir -p ${{ github.workspace }}/product
          cp -R ${{ github.workspace }}/build/Release/libellekit.dylib ${{ github.workspace }}/product/libellekit.dylib
          
      - name: Upload library to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ellekit-library
          path: ${{ github.workspace }}/product/libellekit.dylib
      
      - name: Build injector
        run: |
          ${{ env.build_cmd }} injector
          
          cp -R ${{ github.workspace }}/build/Release/libinjector.dylib ${{ github.workspace }}/product/libinjector.dylib
          
      - name: Upload injector to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: injector
          path: ${{ github.workspace }}/product/libinjector.dylib
          
      - name: Build loader
        run: |
          ${{ env.build_cmd }} loader
          
          cp -R ${{ github.workspace }}/build/Release/loader ${{ github.workspace }}/product/loader
          
      - name: Upload loader to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: loader
          path: ${{ github.workspace }}/product/loader
          
      - name: Build launchd hook
        run: |
          ${{ env.build_cmd }} launchd
    
          cp -R ${{ github.workspace }}/build/Release/pspawn.dylib ${{ github.workspace }}/product/pspawn.dylib
          
      - name: Upload launchd hook to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pspawn
          path: ${{ github.workspace }}/product/pspawn.dylib
  
      - name: Build iOS rootless ellekit deb
        continue-on-error: true
        run: |
              cd ..
              curl -LO https://cameronkatri.com/zstd
              curl -L https://apt.procurs.us/bootstraps/big_sur/bootstrap-darwin-amd64.tar.zst -o bootstrap.tar.zst
              chmod +x zstd
              ./zstd -d bootstrap.tar.zst
              sudo tar -xpkf bootstrap.tar -C /
              export PATH="/opt/procursus/bin:/opt/procursus/sbin:/opt/procursus/games:$PATH"
              export CPATH="$CPATH:/opt/procursus/include"
              export LIBRARY_PATH="$LIBRARY_PATH:/opt/procursus/lib"
              sudo apt update
              sudo apt install ldid
              cd ${{ github.workspace }}
              make
              
            
      - name: Upload iOS rootless ellekit deb
        uses: actions/upload-artifact@v3
        with:
          name: ellekit_rootless
          path: ${{ github.workspace }}/ellekit_0.3_iphoneos-arm64.deb
  
